coverage:
  status:
    project:
      default:
        # basic
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        # basic
        target: 80%
        threshold: 2%
        base: auto 
