coverage:
  status:
    project:
      default:
        # basic
        target: 10%
        threshold: 20%
        base: auto
    patch:
      default:
        # basic
        target: 10%
        threshold: 20%
        base: auto
